service: dio-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: '20201221'
  region: us-east-1
  iam:
      role:
          statements:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:GetItem
                - dynamodb:Scan
              Resource:
                - arn:aws:dynamodb:us-east-1:147531262553:table/ItemTableNew

functions:
  hello:
    handler: src/hello.handler
    events:
      - http:
          path: /
          method: get
  insertitem:
    handler: src/insertItem.handler
    events:
      - http:
          path: /item
          method: post
  fetchitems:
    handler: src/fetchItems.handler
    events:
      - http:
          path: /items
          method: get
  fetchitem:
    handler: src/fetchItem.handler
    events:
      - http:
          path: /items/{id}
          method: get
  updateitem:
    handler: src/updateItem.handler
    events:
      - http:
          path: /items/{id}
          method: put
          
resources:
  Resources:
    ItemTable:
      Type: AWS::DynamoDB::Table
      Properties:
          TableName: ItemTableNew
          BillingMode: PAY_PER_REQUEST
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
          KeySchema:
            - AttributeName: id
              KeyType: HASH
